[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "asreview"
version = "2.0.0-alpha0"
readme = "README.md"
requires-python = ">=3.7"

[project.optional-dependencies]
test = ["pytest"]
