[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "privacy-patterns-3"
version = "0.1.0-alpha0"
readme = "README.md"
requires-python = ">=3.7"

[project.optional-dependencies]
testing = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
